In [1]:
import pandas as pd
import numpy as np
import matplotlib as mp
import seaborn as sbs

df = pd.read_csv('./worldBank.csv', index_col = 0)
df.head()

,Country Code,"Population, total",Population growth (annual %),Surface area (sq. km),Poverty headcount ratio at national poverty lines (% of population),"GNI, Atlas method (current US$)","GNI per capita, Atlas method (current US$)","GNI, PPP (current international $)","GNI per capita, PPP (current international $)",Income share held by lowest 20%,...,Antiretroviral therapy coverage (% of people living with HIV),"Labor force, female (% of total labor force)","Mortality rate, adult, male (per 1,000 male adults)","Mortality rate, adult, female (per 1,000 female adults)",Number of infant deaths,Number of maternal deaths,Number of neonatal deaths,"Patent applications, nonresidents","Patent applications, residents",People practicing open defecation (% of population)
Time Code,,,,,,,,,,,,,,,,,,,,,
YR2000,AFG,20779953.0,2.975053,652860.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,32.478695,333.875,287.786,90127.0,15000.0,62440.0,NaN,NaN,26.019658
YR2000,ALB,3089027.0,-0.637357,28750.0,NaN,3.409087e+09,1100.0,1.229371e+10,3980.0,NaN,...,NaN,41.132334,124.340,65.051,1205.0,12.0,590.0,NaN,NaN,0.864679
YR2000,DZA,31042235.0,1.358408,2381740.0,NaN,4.949310e+10,1590.0,2.408470e+11,7760.0,NaN,...,8.0,13.517815,158.714,122.258,20630.0,980.0,12949.0,127.0,32.0,6.382788
YR2000,ASM,57821.0,1.337137,200.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YR2000,AND,65390.0,1.572166,470.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,2.0,NaN,NaN,0.000000

In [2]:
df.isnull().sum()

Country Code                                                              0
Population, total                                                         6
Population growth (annual %)                                              6
Surface area (sq. km)                                                    36
Poverty headcount ratio at national poverty lines (% of population)    3182
                                                                       ...
Number of maternal deaths                                               576
Number of neonatal deaths                                               432
Patent applications, nonresidents                                      1994
Patent applications, residents                                         2103
People practicing open defecation (% of population)                     195
Length: 62, dtype: int64